## Automatically generated by odin 1.4.7 - do not edit
model_deterministic_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "model_deterministic_rhs_dde",
      rhs_desolve = "model_deterministic_rhs_desolve",
      initmod_desolve = "model_deterministic_initmod_desolve",
      output_dde = "model_deterministic_output_dde"),
    dll = "metapopdeterministic",
    user = c("I_ini", "N_steps", "S_ini", "T_waning", "asympt_frac",
             "asympt_infect", "beta_day", "beta_mode", "beta_strain",
             "cross_protection", "hosp_prob", "icu_prob", "import_vec",
             "infectious_period", "latent_period", "length_hosp",
             "length_icu", "log_beta_ini", "mixing_matrix", "n_strain",
             "n_vac", "post_icu", "pre_icu", "pre_sympt_infect",
             "pre_sympt_period", "prob_death_hosp", "prob_death_icu",
             "prob_death_non_hosp", "susceptibility_asymp",
             "susceptibility_symp", "symp_trans", "sympt_frac",
             "time_before_death", "time_before_death_hosp",
             "time_before_death_icu", "transmisibility", "vaccinations",
             "waning_immunity_vax", "waning_inf", "A_ini", "B_D_H_ini",
             "B_D_ICU_ini", "B_D_ini", "D_ini", "Ea_ini", "Es_ini", "H_ini",
             "ICU_H_ini", "ICU_P_ini", "ICU_R_ini", "I_imp_ini", "P_ini",
             "R_ini", "beta_norm", "expected_health_loss",
             "incidence_steps_measurement", "include_waning", "n",
             "rand_beta_days", "spont_behav_change_params", "threshold_ini",
             "threshold_max", "threshold_min", "tot_hosp_ini",
             "tot_infected_ini", "tot_resp_ini", "tot_vac_adm_ini",
             "tot_vac_ini", "vac_struct_length", "vax_type",
             "waning_immunity"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("model_deterministic_rhs_dde", package = "metapopdeterministic")
        .C("model_deterministic_rhs_desolve", package = "metapopdeterministic")
        .C("model_deterministic_initmod_desolve", package = "metapopdeterministic")
        .C("model_deterministic_output_dde", package = "metapopdeterministic")
      }
    },

    ## This only does something in delay models
    set_initial = function(t, y, use_dde) {
      .Call("model_deterministic_set_initial", private$ptr, t, y, use_dde,
            PACKAGE= "metapopdeterministic")
    },

    update_metadata = function() {
      meta <- .Call("model_deterministic_metadata", private$ptr,
                    PACKAGE = "metapopdeterministic")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, FALSE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("model_deterministic_create", user, PACKAGE = "metapopdeterministic")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/model_deterministic.json", mustWork = TRUE,
                             package = "metapopdeterministic")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("model_deterministic_set_user", private$ptr, user, PACKAGE = "metapopdeterministic")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(t) {
      .Call("model_deterministic_initial_conditions", private$ptr, t, PACKAGE = "metapopdeterministic")
    },

    rhs = function(t, y) {
      .Call("model_deterministic_rhs_r", private$ptr, t, y, PACKAGE = "metapopdeterministic")
    },

    deriv = function(t, y) {
      self$rhs(t, y)
    },

    contents = function() {
      .Call("model_deterministic_contents", private$ptr, PACKAGE = "metapopdeterministic")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_ode(
        self, private, t, y, ..., use_names = use_names)
    }
  ))


model_deterministic <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("model_deterministic")
  model_deterministic_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(model_deterministic) <- "odin_generator"
attr(model_deterministic, "generator") <- model_deterministic_
